// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Concept Pet",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Concept Pet",
            targets: ["AppModule"],
            bundleIdentifier: "ak.Concept-Pet",
            teamIdentifier: "C5A4Q7BH32",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .beachball),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [.process("Resources")]
        )
    ],
    swiftLanguageVersions: [.v6]
)
